cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', get_cart, name='cart_detail'),
    path('add/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('remove/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
]

myshop/urls.py
from django.urls import path
from . import views

app_name = 'myshop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'
         ),
    path('<int:id>/<slug:slug>', views.product_detail,
         name='product_detail')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('myshop.urls', namespace='shop'))

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.contenttypes.models import ContentType


class Cart(models.Model):
    creation_date = models.DateTimeField(verbose_name=_('creation date'))
    checked_out = models.BooleanField(
        default=False, verbose_name=_('checked out'))

    class Meta:
        verbose_name = _('cart')
        verbose_name_plural = _('carts')
        ordering = ('-creation_date',)

    def __unicode__(self):
        return unicode(self.creation_date)


class ItemManager(models.Manager):
    def get(self, *args, **kwargs):
        if 'product' in kwargs:
            kwargs['content_type'] = ContentType.objects.get_for_model(
                type(kwargs['product']))
            kwargs['object_id'] = kwargs['product'].pk
            del (kwargs['product'])
        return super(ItemManager, self).get(*args, **kwargs)

    def filter(self, *args, **kwargs):
        if 'product' in kwargs:
            kwargs['content_type'] = ContentType.objects.get_for_model(
                type(kwargs['product']))
            kwargs['object_id'] = kwargs['product'].pk
            del (kwargs['product'])
        return super(ItemManager, self).filter(*args, **kwargs)


class Item(models.Model):
    cart = models.ForeignKey(Cart, verbose_name=_(
        'cart'), on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name=_('quantity'))
    unit_price = models.DecimalField(
        max_digits=18, decimal_places=2, verbose_name=_('unit price'))
    # product as generic relation
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()

    objects = ItemManager()

    class Meta:
        verbose_name = _('item')
        verbose_name_plural = _('items')
        ordering = ('cart',)

    def __unicode__(self):
        return u'%d units of %s' % (self.quantity, self.product.__class__.__name__)

    def total_price(self):
        return self.quantity * self.unit_price

    total_price = property(total_price)

    # product
    def get_product(self):
        return self.content_type.get_object_for_this_type(pk=self.object_id)

    def set_product(self, product):
        self.content_type = ContentType.objects.get_for_model(type(product))
        self.object_id = product.pk

    product = property(get_product, set_product)

myshop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myshop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=150, db_index=True)
    slug = models.CharField(max_length=150, db_index=True, unique=True)
    image = models.ImageField(upload_to='product/%Y/%m/%d', blank=True)
    description = models.TextField(max_length=1000, blank=True)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    uploaded = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'), )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myshop:product_detail', args=[self.id, self.slug])

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    # HiddenInput чтоб пользователь не видел его в форме
    update = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from .cart import Cart
from myshop.models import Product
from django.shortcuts import render


def add_to_cart(request, product_id, quantity=1):
    product = Product.objects.get(id=product_id)
    cart = Cart(request)
    cart.add(product, product.unit_price, quantity)
    return render(request, 'cart/cart.html', {'cart': Cart(request)})


def remove_from_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    cart = Cart(request)
    cart.remove(product)
    return render(request, 'cart/cart.html', {'cart': Cart(request)})


def get_cart(request):
    return render(request, 'cart/cart.html', {'cart': Cart(request)})

myshop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html',
                  {
                      'category': category,
                      'categories': categories,
                      'products': products
                  })


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product,
                                                        'cart_product_form': cart_product_form})

cart/templates/cart/cart.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
Корзина покупок
{% endblock %}
{% block content %}
<h1>Корзина покупок</h1>
<table class="cart">
    <thead>
        <tr>
            <th>Картинка</th>
            <th>Товар</th>
            <th>Обновить кол-во</th>
            <th>Удалить</th>
            <th>Кол-во</th>
            <th>Цена за шт</th>
            <th>Общая стоимость</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart %}
        {% with product=item.product %}
        <tr>
            <td>
                <a href="{{ product.get_absolute_url }}">
                    <img src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static "img/no_image.png" %}
                                {% endif %}">
                </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
                <form action="{% url 'cart:add_to_cart' product.id %}" method="post">
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.update }}
                    <input type="submit" value='Обновить'>
                    {% csrf_token %}
                </form>
            </td>
            <td><a href="{% url 'cart:remove_from_cart' product.id %}">Удалить</a></td>
            <td>
                {{ item.quantity }}
            </td>
            <td class="num">${{ item.unit_price }}</td>
            <td class="num">${{ item.total_price }}</td>
        </tr>
        {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Всего</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
    </tbody>
</table>
<p class="text-right">
    <a href="{% url "shop:product_list" %}" class="button light">В магазин</a>
    <a href="#" class="button">Оформить заказ</a>
</p>
{% endblock %}

myshop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}Мой магазин{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>

<body>
    <div id="header">
        <a href="/" class="logo">Мой магазин</a>
    </div>
    <div id="subheader">
        <div class="cart">
            {% if cart.count > 0 %}
            В корзине:
            <a href="{% url "cart:cart_detail" %}">
                {{ cart.count }} item,
                ${{ cart.summary }}
            </a>
            {% else %}
            Корзина пустая
            {% endif %}
        </div>
    </div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>

</html>

myshop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}
{% static "img/no_image.png" %}{% endif %}">
    <h1>{{ product.name }}</h1>
    <h2>
        <a href="{{ product.category.get_absolute_url }}">{{product.category }}</a>
    </h2>
    <p class="price">${{ product.unit_price }}</p>
    <form action="{% url 'cart:add_to_cart' product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value='В корзину'>
    </form>
    {{ product.description|linebreaks }}
</div>
{% endblock %}

myshop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}
<div id="sidebar">
    <h3>Категория</h3>
    <ul>
        <li {% if not category %}class="selected" {% endif %}>
            <a href="{% url 'shop:product_list' %}">Все</a>
        </li>
        {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected" {% endif %}>
            <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
<div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Товар{% endif %}</h1>
    {% for product in products %}
    <div class="item">
        <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.image %}{{ product.image.url }}{%else %}{% static 'img/no_image.png' %}{% endif %}">
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
        <br>
        ${{ product.unit_price }}
    </div>
    {% endfor %}
</div>
{% endblock %}